### vars
@livehost = https://auth.knight.works/api/v1
@port = 3131
@localhost = http://localhost:{{port}}/api/v1
@contentType = application/json

### verify
GET {{localhost}}/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksImVtYWlsIjoiam9yZGFuKzE0QGtuaWdodC53b3JrcyIsInNpdGUiOiJjbG91ZC5rbmlnaHQud29ya3MiLCJpYXQiOjE1NzI3MjI0NjgsImV4cCI6MTU3MjgwODg2OH0.WHKrboSuJrxjVUdMokc-7qQK6LuCNrq1SMgyY3yd7Mw


###
POST {{localhost}}/register

###
POST http://localhost:3131/api/v1/register
content-type: {{contentType}}

{
    "email": "jordan+16@knight.works",
    "password": "test",
    "site": "cloud.knight.works"
}
####
POST {{localhost}}/login
content-type: {{contentType}}

{
    "email": "jordan+14@knight.works",
    "password": "test"
}

###
POST {{livehost}}/login
content-type: application/json

{
    "email": "test@email.com",
    "password": "test"
}

###
### Refresh
POST {{localhost}}/refresh
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEJJQVVLRmJCakk2dGxHQVFxVTNHNnViQUNLS2tTZWkyUGNxRlZESE1acmU2VEJtekUwOGpTIiwiaWF0IjoxNTcyNzIzMzM2fQ.H94OYXkcQKEsaYP4m549g47ch5VfJA_1v2RtU-_JsMs"
}

### Refresh
POST {{localhost}}/logout
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEJJQVVLRmJCakk2dGxHQVFxVTNHNnViQUNLS2tTZWkyUGNxRlZESE1acmU2VEJtekUwOGpTIiwiaWF0IjoxNTcyNzIzMzM2fQ.H94OYXkcQKEsaYP4m549g47ch5VfJA_1v2RtU-_JsMs"
}


###