### vars
@livehost = https://auth.knight.works/api/v1
@port = {{$processEnv PORT}}
@localhost = http://localhost:{{port}}/api/v1
@contentType = application/json

### verify
GET {{livehost}}/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsImlhdCI6MTU3MTc1MjQwNiwiZXhwIjoxNTcxNzUzMDA2fQ.16AN6x_LfeqjQmhkgT27rKNNjDVZi-6B19RiyYfeUwQ

###
{{localhost}}/register

###
POST http://localhost:3131/api/v1/register
content-type: {{contentType}}

{
    "email": "jordan+2@knight.works",
    "password": "test",
    "url": "cloud.knight.works"
}
####
POST {{localhost}}/login
Content-type: {{contentType}}

{
    "email": "test@email.com",
    "password": "test"
}

###
POST {{livehost}}/login
content-type: application/json

{
    "email": "test@email.com",
    "password": "test"
}